name: C++ Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache g++
      uses: actions/cache@v2
      with:
        path: /usr/bin/g++
        key: ${{ runner.os }}-gpp-${{ hashFiles('**/library_management.cpp') }}

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build
      run: |
        g++ -o LibraryManagementSystem library_management.cpp
        if [ $? -eq 0 ]; then
          echo "Build successful!"
        else
          echo "Build failed!"
          exit 1
        fi

    - name: Run Program
      run: |
        ./LibraryManagementSystem
