name: C++ Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install g++

    - name: Build
      run: |
        g++ -o LibraryManagementSystem libiry_managmen.cpp  # Change main.cpp to your main file name
        ./library_management                  # Run the executable

    - name: Run Tests (if applicable)
      run: |
        ./library_management                  # Adjust based on your testing setup
