name: C++ Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build
      run: |
        g++ -o LibraryManagementSystem libiry_managmen.cpp  # Replace with your main file name
        if [ $? -eq 0 ]; then                # Check if build was successful
          echo "Build successful!"
        else
          echo "Build failed!"
          exit 1
        fi

    - name: Run Program
      run: |
        ./libiry_managmen                  # Adjust based on your main program's execution
